version: "3.8"

services:
  cells-web:
    build:
      context: ./cells-web
      dockerfile: Dockerfile.dev
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.dev-cells-web.rule=Host(`cells.lavrentev.dev`)
      - traefik.http.routers.dev-cells-web.entrypoints=https
      - traefik.http.routers.dev-cells-web.tls.certresolver=simple-resolver
      - traefik.http.services.dev-cells-web.loadbalancer.server.port=8132
    volumes:
      - ./cells-web:/app
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik